set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '10'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g mode-keys vi

set -g base-index 1

bind r source-file ~/.tmux.conf; display "Configuration reloaded"

# Get to the last active window
bind s last-window

# 256 Colours
set -g default-terminal "screen-256color"

set -g mouse off

# rebind prefix to Ctrl-s
unbind C-b
unbind C-s
bind w choose-tree -s
set -g prefix C-s
bind C-s send-prefix

bind h select-pane -L  # Move to the pane on the left
bind j select-pane -D  # Move to the pane below
bind k select-pane -U  # Move to the pane above
bind l select-pane -R  # Move to the pane on the right

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# 256 Colours
set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "screen-256color"

# Open panes in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Set window notifications
setw -g monitor-activity off
set -g visual-activity off

# Automatically set window title
setw -g automatic-rename on

set -g status-interval 1

set -g status-bg black
if-shell '[ -n "$SSH_CONNECTION" ]' 'set -g status-bg magenta'
set -g status-fg white
if-shell '[ -n "$SSH_CONNECTION" ]' 'set -g status-fg black'

run '~/.tmux/plugins/tpm/tpm'
