#!/bin/sh

execdir () {
    if [ -d "$1" ]; then
        for f in "$1"/*; do
            if [ -x "$f" ]; then . "$f" ; fi
        done
        unset f
    fi
}

execdir /etc/X11/xinit/xinitrc.d

# Keyboard and mouse rate; increases their responsiveness 
xset r rate 180                                           
xset mouse 22/7 1                                         
                                                          
# Keyboard settings
# -layout us,il,ru      Configure layouts
# -option ''            Reset all previously set options
# grp:alt_shift_toggle  Switch between layouts using alt-shift
# grp_led:scroll        Light the scroll LED depending on layout
# compose:rctrl         Use right control as the compose key
# caps:swapescape       Swap escape and capslock
setxkbmap \
    -layout us,il,ru \
    -variant dvorak,,winkeys \
    -option '' \
    -option grp:alt_shift_toggle \
    -option grp_led:scroll \
    -option compose:rctrl \
    -option caps:swapescape

# Urxvt daemon, for faster urxvt   
urxvtd -q -o -f

# Automatically loads the last wallpaper that was set up with feh
[ -e ~/.fehbg ] && sh ~/.fehbg

# Cursor theme (requires xcursor-neutral)
xsetroot -cursor_name Neutral

# Merge the custom Xresources settings with the default ones
xrdb -merge ~/.Xresources

# Java settings

# Make fonts look at least half-decent
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
# Fix for tiling window managers
export _JAVA_AWT_WM_NONREPARENTING=1

