" Neovim compatability
if has('nvim')
    let $VIMDIR=$HOME.'/.config/nvim'
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
    let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1
else
    let $VIMDIR=$HOME.'/.vim'
    set nocompatible
endif

" Properties
set encoding=utf8       " Use UTF8 everywhere
set showmatch           " Show matching brackets
set lazyredraw          " Redraw only when we need to
set autoread            " Automatically reload file on external changes
set report=0            " Don't hide messages
set clipboard=unnamed   " Share clipboard with system clipboard

" Tabs & Spaces
set expandtab     " Use spaces instead of tabs
set tabstop=4     " A tab is 4 spaces
set autoindent    " Always set autoindenting on
set copyindent    " Copy the previous indentation on autoindenting
set shiftwidth=4  " Number of spaces to use for autoindenting
set smarttab      " Insert tabs on the start of a line according to shiftwidth, not tabstop

augroup filetype_specific
    au!
    au FileType make :setlocal ts=8 sw=8 sts=0 noet
augroup END

" Search
set ignorecase    " Ignore case when searching
set smartcase     " Ignore case if search pattern is all lowercase, case-sensitive otherwise
set hlsearch      " Highlight search terms
set incsearch     " Show search matches as you type

" Backups
set swapfile
set backup
set backupdir=$VIMDIR/bak
set directory=$VIMDIR/tmp

" No annoyances
set novisualbell        " No blinking
set noerrorbells        " No noise
set vb t_vb=            " Disable any beeps or flashes on error

" Key Bindings

" Cleans hilighted text after search
nmap <silent> <leader>/ :nohlsearch<CR>

call plug#begin($VIMDIR.'/bundle')

" Colorschemes
Plug 'chriskempson/base16-vim'
let base16colorspace=256

call plug#end()

" set syntax on after vim-plug does it's thing
filetype plugin indent on
syntax on " Enable syntax highlighting

colorscheme base16-default

