#!/usr/bin/env sh

# If using nvidia, execute some stuff that supposedly improves performance
# https://wiki.archlinux.org/index.php/Nvidia#GUI:_nvidia-settings
if [ $(lsmod | grep nvidia &> /dev/null) ]; then
    nvidia-settings --load-config-only
    nvidia-settings -a InitialPixmapPlacement=2
fi
