vim.keymap.set("n", "-", "<cmd>Oil --float<CR>", { desc = "Open dir in oil" })
vim.keymap.set("n", "<leader>h", "<cmd>nohlsearch<CR>", { desc = "Disable search highlight" })

local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, { desc = 'Telescope live grep' })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = 'Telescope buffers' })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = 'Telescope help tags' })

-- LSP
vim.keymap.set('n', 'K', vim.lsp.buf.hover)
vim.keymap.set('n', '<leader>k', vim.diagnostic.open_float)
vim.keymap.set('n', 'gd', vim.lsp.buf.definition)
vim.keymap.set('n', 'gD', vim.lsp.buf.declaration)
vim.keymap.set('n', 'gi', vim.lsp.buf.implementation)
vim.keymap.set('n', 'go', vim.lsp.buf.type_definition)
vim.keymap.set('n', 'gr', vim.lsp.buf.references)
vim.keymap.set('n', 'gs', vim.lsp.buf.signature_help)
vim.keymap.set('n', '<F2>', vim.lsp.buf.rename)
vim.keymap.set('n', '<F4>', vim.lsp.buf.code_action)
vim.keymap.set("n", "<leader>lq", vim.diagnostic.setqflist, { desc = "Diagnostics → Quickfix" })
vim.keymap.set("n", "<leader>ll", vim.diagnostic.setloclist, { desc = "Diagnostics → Loclist" })
