# Path to the oh-my-zsh configuration
ZSH=$HOME/.config/oh-my-zsh

# Use theme from $ZSH/themes/
ZSH_THEME="robbyrussell"

# Disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Load plugins from $ZSH/plugins/
plugins=(git virtualenv common-aliases colored-man extract)

source $ZSH/oh-my-zsh.sh

# Customs

for dir in \
    /usr/local/sbin \
    /usr/local/bin \
    /usr/bin \
    /usr/bin/core_perl \
    $HOME/go/bin \
    $HOME/.cabal/bin \
    $HOME/.local/bin \
    $HOME/.gem/ruby/2.1.0/bin \
    $HOME/android-sdks/platform-tools \
    $HOME/android-sdks/tools \
; do
    if [[ -d "$dir" ]]; then 
        if [[ "$dir" == "$HOME/go/bin" ]]; then
            export GOPATH=$HOME/go
        fi
        path+="$dir" 
    fi
done

# Remove duplicates from $PATH
typeset -U PATH

export EDITOR=vim

# Commands
pyhelp() { python -c "help($@)"; }
