# Path to your oh-my-zsh configuration.
ZSH=$HOME/.config/oh-my-zsh

ZSH_THEME="robbyrussell"

# Uncomment this to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

plugins=(git virtualenv common-aliases colored-man extract)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/core_perl:$HOME/.local/bin:$GOPATH/bin:~/.gem/ruby/2.0.0/bin

export EDITOR=vim
