#!/usr/bin/env bash

# enable colors for grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# some ls aliases
alias ls='ls --group-directories-first --color=auto -Fh'
alias ll='ls -l'
alias la='ls -lA'
alias l='ll'

# file and dir stuff
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias rm='rm -I --preserve-root'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# python
pyhelp() {
    python3 -c 'help('"$@"')'
}

# improved ps | grep alias
psgrep() {
    ps auxf | grep "$@" | grep -v grep;
}

# colored man
man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[01;38;5;74m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[38;5;246m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[04;38;5;146m' \
    man "$@"
}

# mkdir && cd
mkcd() {
    mkdir -p "$@" && cd "$@"
}

# livestreamer
alias livestreamer='livestreamer --default-stream best -p mpv'

# misc
alias sprunge='curl -F "sprunge=<-" http://sprunge.us'
