#!/usr/bin/env bash

# enable colors for grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# some ls aliases
alias ls='ls --color'
alias l='ls -lFh'
alias ll='l'
alias la='l -lA'

# file and dir stuff
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias rm='rm -Iv --preserve-root'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# python
pyhelp() {
    python3 -c 'help('"$@"')'
}

# improved ps | grep alias
psgrep() {
    ps auxf | grep "$@" | grep -v grep;
}

# colored man
man() {
    env \
    LESS_TERMCAP_mb=$'\E[1;31m' \
    LESS_TERMCAP_md=$'\E[1;31m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[1;44;33m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[1;32m' \
    man "$@"
}

# mkdir && cd
mkcd() {
    mkdir -p "$@" && cd "$@"
}

# livestreamer
alias livestreamer='livestreamer --default-stream best -p mpv'

# misc
alias sprunge='curl -F "sprunge=<-" http://sprunge.us'
alias netflix='google-chrome-stable --proxy-server="socks5://localhost:1234" --app="https://netflix.com"'
